
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: build-and-deploy-
spec:
  serviceAccountName: pipeline
  pipelineRef:
    name: build-and-deploy
  resources:
    - name: api-repo
      resourceRef:
        name: api-repo
    - name: api-image
      resourceRef:
        name: api-image