apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-maven-settings
data:
  settings.xml: |
    <?xml version="1.0"?>
    <settings>
      <mirrors>
        <mirror>
          <id>Nexus</id>
          <name>Nexus Public Mirror</name>
          <url>http://nexus-task-demo-nexus.apps-crc.testing/repository/maven-all-public/</url>
          <mirrorOf>*</mirrorOf>
        </mirror>
      </mirrors>
      <servers>
        <server>
          <id>nexus</id>
          <username>admin</username>
          <password>app_deploy</password>
        </server>
      </servers>
    </settings>