---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: api-repo
spec:
  type: git
  params:
    - name: url
      value: https://github.com/bootlessxfly/tekton-tasks-demo
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: api-image
spec:
  type: image
  params:
    - name: url
      value: image-registry.openshift-image-registry.svc:5000/pipeline-tasks-demo/tekton-tasks-demo:latest
#---
#apiVersion: tekton.dev/v1alpha1
#kind: PipelineRun
#metadata:
#  name: build-and-deploy
#  namespace: pipeline-tasks-demo
#spec:
#  serviceAccountName: build-bot
#  pipelineRef:
#    name: build-and-deploy