apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: tekton-tasks-demo
#    app.kubernetes.io/component: web
#    app.kubernetes.io/instance: spring-petclinic
#    app.kubernetes.io/name: spring-petclinic
#    app.kubernetes.io/part-of: spring-petclinic
    app.openshift.io/runtime: eap71
  name: tekton-tasks-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tekton-tasks-demo
  template:
    metadata:
      labels:
        app: tekton-tasks-demo
    spec:
      containers:
      - name: tekton-tasks-demo
        imagePullPolicy: Always
        image: image-registry.openshift-image-registry.svc:5000/pipeline-tasks-demo/tekton-tasks-demo:latest
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 45
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        ports:
        - containerPort: 8080
          protocol: TCP
#        - containerPort: 8443
#          protocol: TCP
#        - containerPort: 8778
#          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 45
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
