apiVersion: v1
kind: Service
metadata:
  labels:
    app: tekton-tasks-demo
  name: tekton-tasks-demo
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9990
      targetPort: 9990
  selector:
    app: tekton-tasks-demo